//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeverBadWeather.Infrastructure.WeatherForecastService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeverBadWeather.Infrastructure.WeatherForecastService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunenummer	Stadnamn	Prioritet	Stadtype nynorsk	Stadtype bokmÃ¥l	Stadtype engelsk	Kommune	Fylke	Lat	Lon	HÃ¸gd	Nynorsk	BokmÃ¥l	Engelsk	
        ///101	Asak kirke	55	Kyrkje	Kirke	Church	Halden	Ã˜stfold	59.14465	11.45458		http://www.yr.no/stad/Noreg/Ã˜stfold/Halden/Asak_kirke/varsel.xml	http://www.yr.no/sted/Norge/Ã˜stfold/Halden/Asak_kirke/varsel.xml	http://www.yr.no/place/Norway/Ã˜stfold/Halden/Asak_kirke/forecast.xml
        ///101	Berg kirke	36	Kyrkje	Kirke	Church	Halden	Ã˜stfold	59.13783	11.32945		http://www.yr.no/stad/Nor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string noreg {
            get {
                return ResourceManager.GetString("noreg", resourceCulture);
            }
        }
    }
}
